# -*- coding: utf-8 -*-
"""06-01-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-kNaAi3sZMwFvqUGKcGVr_p08Bm1uFG
"""

my_int = 42
print("Original Integer:", my_int)

my_list = [1,'hello',3.14,True]
print("Original List:",my_list)
#adding an element to list
my_list.append('World')
print("list after appending World: ",my_list)
#removing an element
my_list.remove(3.14)
print("list after removing 3.14: ",my_list)

my_tuple = (1,'apple',3.14,False)
print("Original tuple: ",my_tuple)
print("First element: ",my_tuple[0])
print("Last element: ",my_tuple[-1])

#For loop to print numbers 1 to 5
for i in range(1,6):
    print(i)

#While loop to print numbers 1 to 5
t = 1
while t<=5:
    print(t)
    t+=1#to increment by

number = int(input("Enter a number: "))
if number > 0:
    print(f"{number} is a positive number.")
elif number < 0:
    print(f"{number} is a negative number.")
else:
    print(f"{number} is zero.")

def greet(name):
  """Takes a name as an argument and prints a greeting."""
  print(f"Hello from function, {name}!")
greet("Alice")