# -*- coding: utf-8 -*-
"""07-01-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJp4Gm3p3gp3EjdY2AYpAid_ZgFIQ0N7
"""

a = "hello world"
b = a.upper()
print(b)

a = "HELLO WORLD"
b = a.lower()
print(b)

a = "hello World"
b = a.replace('hello', 'hi')
print(b)

a = range(10)
b = list(a)
print(b)

#start , stop then steps
my_list = list(range(5,15,2))
print(my_list)

def add_numbers (a,b):
  result = a + b
  return result
print(add_numbers(10,4))

def greet(name, greeting="hello"):
  print(f"[greeting], {name}!")
def calculate_sum(*args):
  total = sum(args)
  return total
print("Sum of 1,2,3:",calculate_sum(1,2,3))
print("Sum of 1,2,3,4:",calculate_sum(1,2,3,4))

correct_username ='admin'
correct_password = '123'
while True:
  username = input("Enter your username: ")
  password = input("Enter your password: ")
  if username == correct_username and password == correct_password:
    print("Login successful!")
    break
  else:
    print("Invalid username or password. Please try again.")

def square(num):
    return num ** 2
numbers = list(map(int, input("Enter numbers: ").split()))
squared_numbers = list(map(square, numbers))
total_sum = sum(squared_numbers)
print("Squared Numbers:", squared_numbers)
print("Sum of Squares:", total_sum)

def count_vowels(s):
    vowels = "aeiouAEIOU"
    count = 0
    for char in s:
        if char in vowels:
            count += 1
    return count
input_string = input("Enter a string: ")
substring_index = input_string.find("world")
stripped_string = input_string.strip()
vowel_count = count_vowels(stripped_string)
print("Original String:", input_string)
print("Stripped String:", stripped_string)
print("Index of 'world':", substring_index)
print("Number of vowels:", vowel_count)