# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11TNvR76JMo5s-0Kn0Ad_b0nYhyQoOc6q
"""

#Write a Python program to calculate the sum of all even numbers between 1 and a given positive integer n
def sum_of_even_numbers(n):
    total = 0
    for i in range(2, n+1, 2):
        total += i
    return total
n = int(input("Enter a positive integer: "))
if n > 0:
    result = sum_of_even_numbers(n)
    print(f"The sum of all even numbers between 1 and {n} is: {result}")
else:
    print("Please enter a positive integer.")