# -*- coding: utf-8 -*-
"""DAY-5 Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107F8BTRwMn5afi8E32V7H0J_h1Vnj5a5
"""

#write a python program to calculate the frequency of each word in a given text.print the words and their corresponding counts
# Function to calculate word frequency
def word_frequency(text):
    words = text.lower().split()
    word_count = {}
    for word in words:
        if word in word_count:
            word_count[word] += 1
        else:
            word_count[word] = 1

    # Print the word counts
    for word, count in word_count.items():
        print(f"{word}: {count}")

# Sample text input
text = "Hello world! Hello everyone. Welcome to the world of Python. Python is great!"

# Call the word_frequency function
word_frequency(text)