# -*- coding: utf-8 -*-
"""NLP(AD).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-qqvSY-lORjPEV4urp0Ut-mEdF6XXLfT
"""

my_list = [1, 3, "hello",True]
print(my_list)

my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
sliced_list = my_list[2:5]
print(sliced_list)

my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

sliced_list = my_list[-2:]
print(sliced_list)


sliced_list = my_list[::-1]
print(sliced_list)

students_data = [
    [18, 5, 75],
    [20, 3, 65],
    [22, 8, 85],
    [19, 4, 72],
    [21, 6, 78]
]

marks = [student[-1] for student in students_data]
print("Marks:", marks)